package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
	"time"

	"golang.org/x/net/publicsuffix"
)

// Embedded templates for Caddyfile generation
var templates = map[string]string{
	TypeExternal: `# {{NETWORK}} - auto-generated by watcher

{{DOMAINS}} {
{{IMPORTS}}
{{ALLOWLIST_BLOCK}}
}
`,
	TypeInternal: `# {{NETWORK}} - auto-generated by watcher

{{DOMAINS}} {
{{IMPORTS}}
    import internal

    handle @internal {
{{AUTH_BLOCK}}{{REVERSE_PROXY_BLOCK}}
    }
    import stealth
}
`,
	TypeCloudflare: `# {{NETWORK}} - auto-generated by watcher

{{DOMAINS}} {
{{IMPORTS}}
    import cloudflare

    handle @cloudflare {
{{AUTH_BLOCK}}{{REVERSE_PROXY_BLOCK}}
    }
    import stealth
}
`,
}

// CaddyManager manages Caddyfile configurations
type CaddyManager struct {
	hostsDir         string
	allowlistManager *AllowlistManager
	configs          map[string]*CaddyConfig // configKey (container_network) -> config
	// absentSince haelt fest, seit wann zu einer Config kein Container mehr
	// laeuft. Der State ist bewusst nur im Speicher: geht er bei einem
	// Watcher-Neustart verloren, beginnt die Karenz von vorn. Das verzoegert
	// das Aufraeumen, kann es aber nie verfruehen.
	absentSince map[string]time.Time
	// networkGone ist die zweite, getrennte Uhr: seit wann das Netzwerk einer
	// Config nicht mehr existiert. Getrennt gehalten, weil beide Uhren
	// unabhaengig voneinander zurueckgesetzt werden muessen - eine gemeinsame
	// Map hiesse, dass der 5-Minuten-Sweep die Container-Karenz jedes Mal neu
	// startet und eine verwaiste Config nie verschwaende.
	networkGone map[string]time.Time
	// absentGrace ist ueber CONFIG_CLEANUP_GRACE einstellbar, damit grosse
	// Installationen mit langen Update-Laeufen die Frist hochziehen koennen.
	absentGrace time.Duration
	mu          sync.RWMutex
}

// ConfigInfo holds information about a configuration file
type ConfigInfo struct {
	Network         string
	Container       string
	Type            string
	Domains         []string
	Allowlist       []string
	Logging         bool
	DNSProvider     string
	Compression     bool
	Header          bool
	Auth            bool
	AuthPaths       []string
	AuthExcept      []string
	AuthGroups      []string
	AuthURL         string
	SEO             bool
	SEONoindexTypes []string
	WWWRedirect     bool
	Performance     bool
	Security        bool
	WordPress       bool
	TrustedProxies  []string
	Path            string
	Managed         bool
}

// NewCaddyManager creates a new CaddyManager
func NewCaddyManager(hostsDir string, allowlistManager *AllowlistManager) *CaddyManager {
	return &CaddyManager{
		hostsDir:         hostsDir,
		allowlistManager: allowlistManager,
		configs:          make(map[string]*CaddyConfig),
		absentSince:      make(map[string]time.Time),
		networkGone:      make(map[string]time.Time),
		absentGrace:      defaultAbsentGrace,
	}
}

// resolveTrustedProxies resolves trusted proxies entries (hostnames/IPs) to IPs
func (m *CaddyManager) resolveTrustedProxies(entries []string) []string {
	if len(entries) == 0 || m.allowlistManager == nil {
		return nil
	}

	var allIPs []string
	seen := make(map[string]bool)

	for _, entry := range entries {
		ips := m.allowlistManager.resolveEntry(entry)
		for _, ip := range ips {
			if !seen[ip] {
				seen[ip] = true
				allIPs = append(allIPs, ip)
			}
		}
	}

	return allIPs
}

// ssoCookiePattern removes TinyAuth's cookies from a Cookie header.
//
// Two alternatives, and both need care:
//
//	^(?:tinyauth-[^=;]*=[^;]*(?:;\s*|$))+   leading run of TinyAuth cookies
//	;\s*tinyauth-[^=;]*=[^;]*               any later one, with its separator
//
// The leading alternative repeats (+) on purpose. Replacement scans left to
// right and never rewinds, so after consuming the first cookie the anchor no
// longer matches - without the repetition a second consecutive cookie at the
// start would survive. TinyAuth sets four (session, csrf, redirect, oauth), so
// that case is the norm, not an edge case.
//
// Both alternatives are anchored, either at the start of the header or behind a
// separator. Matching the bare prefix would eat into unrelated cookies: with an
// unanchored pattern, "mytinyauth-session=x; a=1" collapses to "mya=1" - a
// silently corrupted header.
const ssoCookiePattern = `^(?:tinyauth-[^=;]*=[^;]*(?:;\s*|$))+|;\s*tinyauth-[^=;]*=[^;]*`

// ssoCookieStripDirective returns a header_up directive that removes TinyAuth's
// session cookies from the request before it reaches the backend.
//
// TinyAuth scopet sein Cookie auf die Parent-Domain, damit Single Sign-on ueber
// Subdomains funktioniert (Domain=.example.com). Der Browser schickt es damit an
// jede Site UNTERHALB dieser Domain - und dort hat das Backend eine Kredential
// vor sich, die nur TinyAuth braucht. Ein kompromittiertes Backend koennte sie
// gegen jeden anderen geschuetzten Dienst wiederverwenden.
//
// Zwei Faelle bekommen deshalb KEINEN Strip:
//
//   - TinyAuths eigener Host. Er muss seine Sitzung lesen koennen.
//   - Sites ausserhalb des Cookie-Scopes. Der Browser sendet das Cookie
//     ueberhaupt nur an Domains unter dem Scope; auf einer fremden Domain wie
//     kunde.de kann es nie ankommen. Ein Regex-Replace auf dem Cookie-Header
//     jeder Anfrage waere dort Aufwand und Angriffsflaeche ohne Gegenwert.
//
// Der Strip sitzt am reverse_proxy zum BACKEND, nicht auf der Site. Ein
// request_header auf Site-Ebene liefe vor forward_auth, weil Caddy header vor
// handle sortiert - TinyAuth bekaeme eine Anfrage ohne seinen eigenen
// Sitzungscookie und wuerde jede Anmeldung ablehnen. header_up schreibt nur die
// Anfrage nach oben um, der forward_auth-Aufruf bleibt unberuehrt.
//
// Die Cookie-Namen tragen einen aus dem Hostnamen abgeleiteten Suffix
// (tinyauth-session-8b2f3e83, tinyauth-csrf-...), deshalb wird das Praefix
// gematcht.
func ssoCookieStripDirective(cfg *CaddyConfig) string {
	if isTinyauthHost(cfg) {
		return ""
	}
	if !inTinyauthCookieScope(cfg, tinyauthCookieDomain()) {
		return ""
	}
	return `header_up Cookie "` + ssoCookiePattern + `" ""`
}

// tinyauthCookieDomain liefert den Geltungsbereich von TinyAuths Cookies, ohne
// fuehrenden Punkt. Leer bedeutet "unbekannt" - dann wird ueberall gestrippt.
//
// TinyAuth setzt seine Cookies auf die registrierbare Domain, damit SSO ueber
// alle Subdomains funktioniert: Domain=.example.com, unabhaengig davon, wie tief
// TINYAUTH_DOMAIN selbst liegt.
//
// Ermittelt wird sie ueber die Public Suffix List, nicht durch Zaehlen von
// Labels. Eine Faustregel "letzte zwei Labels" liegt bei mehrteiligen Endungen
// daneben: aus auth.example.co.uk wuerde co.uk, und aus auth.example.github.io
// wuerde github.io - beides sind Public Suffixes, keine registrierbaren Domains.
//
// Scheitert die Ermittlung - etwa weil der Host selbst ein Public Suffix ist
// oder die Endung unbekannt -, bleibt der Scope offen und es wird ueberall
// gestrippt. Das ist die unschaedliche Richtung: zu weit heisst ueberfluessig
// strippen, zu eng liesse eine Kredential auf einer Site stehen, die sie erhaelt.
//
// Die Liste ist im Paket einkompiliert und altert mit der Abhaengigkeit. Fuer
// eine neue Endung faellt der Scope dann offen aus - also wieder in die
// unschaedliche Richtung.
func tinyauthCookieDomain() string {
	host := strings.ToLower(strings.TrimSpace(os.Getenv("TINYAUTH_DOMAIN")))
	if host == "" {
		return ""
	}

	scope, err := publicsuffix.EffectiveTLDPlusOne(host)
	if err != nil {
		log.Printf("Cannot determine cookie scope for TINYAUTH_DOMAIN=%q (%v) - stripping the SSO cookie on all sites", host, err)
		return ""
	}
	return scope
}

// inTinyauthCookieScope prueft, ob eine Site das TinyAuth-Cookie ueberhaupt
// erhalten kann. Ist der Scope unbekannt, wird das bejaht - lieber unnoetig
// strippen als eine Kredential durchlassen.
func inTinyauthCookieScope(cfg *CaddyConfig, scope string) bool {
	if scope == "" {
		return true
	}
	for _, d := range cfg.Domains {
		d = strings.ToLower(strings.TrimSpace(d))
		if d == scope || strings.HasSuffix(d, "."+scope) {
			return true
		}
	}
	return false
}

// isTinyauthHost erkennt TinyAuths eigene Site.
//
// Erkannt wird primaer am CONTAINER, nicht an TINYAUTH_DOMAIN. Der Grund ist
// ein realer Ausfall: docker-compose gibt dem Watcher fuer TINYAUTH_DOMAIN
// einen LEEREN Default. Ist die Variable in der .env nicht gesetzt, greift die
// Ausnahme nicht, TinyAuth bekommt seine eigenen Cookies gestrippt und meldet
// beim Login "Failed to get OAuth session cookie". Der Containername ist
// dagegen immer bekannt - das (auth)-Snippet adressiert TinyAuth an genau
// derselben Stelle mit {env.COMPOSE_PROJECT_NAME}-tinyauth-1.
//
// TINYAUTH_DOMAIN bleibt als Ausnahme fuer abweichende Aufbauten bestehen.
func isTinyauthHost(cfg *CaddyConfig) bool {
	if project := strings.TrimSpace(os.Getenv("COMPOSE_PROJECT_NAME")); project != "" {
		tinyauthContainer := project + "-tinyauth-1"
		if cfg.OwnerContainer == tinyauthContainer || cfg.Container == tinyauthContainer {
			return true
		}
	}

	tinyauthDomain := strings.TrimSpace(os.Getenv("TINYAUTH_DOMAIN"))
	if tinyauthDomain == "" {
		return false
	}
	for _, d := range cfg.Domains {
		if strings.EqualFold(strings.TrimSpace(d), tinyauthDomain) {
			return true
		}
	}
	return false
}

// realIPDirective setzt X-Real-IP auf die tatsaechliche Gegenstelle.
//
// Caddy verwaltet diesen Header nicht - gemessen: ein vom Client gesetztes
// "X-Real-IP: 9.9.9.9" erreichte das Backend unveraendert, unabhaengig von
// trusted_proxies. Backends, Rate-Limits, Geo-Sperren und Audit-Logs, die sich
// darauf stuetzen, waeren damit frei steuerbar.
//
// {client_ip} ist nicht ueber X-Forwarded-For beeinflussbar (mit Caddy 2.11.4
// geprueft) und beruecksichtigt eine global konfigurierte trusted_proxies-Liste,
// falls es die einmal gibt.
//
// Der cloudflare-Typ setzt den Header separat aus CF-Connecting-IP - dort ist
// die Gegenstelle Cloudflare, nicht der Besucher.
func realIPDirective() string {
	return "header_up X-Real-IP {client_ip}"
}

// generateReverseProxyBlock generates the reverse_proxy directive with optional trusted_proxies
// indent is the base indentation (e.g., "        " for 8 spaces)
// extraDirectives are optional additional directives inside the block (e.g., "header_up X-Real-IP ...")
func (m *CaddyManager) generateReverseProxyBlock(cfg *CaddyConfig, indent string, extraDirectives ...string) string {
	resolvedProxies := m.resolveTrustedProxies(cfg.TrustedProxies)

	var extras []string
	for _, d := range extraDirectives {
		if d != "" {
			extras = append(extras, d)
		}
	}
	if strip := ssoCookieStripDirective(cfg); strip != "" {
		extras = append(extras, strip)
	}

	// Simple case: nothing to add
	if len(extras) == 0 && len(resolvedProxies) == 0 {
		return indent + "reverse_proxy " + cfg.Upstream
	}

	// Need block format
	var lines []string
	lines = append(lines, indent+"reverse_proxy "+cfg.Upstream+" {")
	for _, d := range extras {
		lines = append(lines, indent+"    "+d)
	}
	if len(resolvedProxies) > 0 {
		// Bewusst OHNE private_ranges.
		//
		// "trusted_proxies" heisst: von diesen Gegenstellen werden
		// X-Forwarded-*-Angaben uebernommen statt ersetzt. Mit private_ranges
		// waere das jeder Container im Docker-Netz - gemessen: ein Client aus
		// einem privaten Netz konnte damit X-Forwarded-For, -Host und -Proto
		// frei setzen und die Werte erreichten das Backend unveraendert. Bei
		// TinyAuth, das seine IP-Regeln auf X-Forwarded-For stuetzt, ist das
		// der Weg zur Umgehung.
		//
		// Vertraut wird nur, was ueber CADDY_TRUSTED_PROXIES ausdruecklich
		// benannt wurde. Ohne die Variable entsteht die Direktive gar nicht und
		// Caddy ersetzt die Angaben - die sichere Voreinstellung.
		lines = append(lines, indent+"    trusted_proxies "+strings.Join(resolvedProxies, " "))
	}
	lines = append(lines, indent+"}")

	return strings.Join(lines, "\n")
}

// generateAuthBlockForHandle generates auth block for inside handle blocks (internal/cloudflare types)
// Uses 8-space indentation instead of 4-space for imports
func (m *CaddyManager) generateAuthBlockForHandle(cfg *CaddyConfig) string {
	// Ein einziger Weg fuer alle Faelle. Der frueher hier stehende Sonderfall
	// fuer Full-Site-Auth erzeugte den Block inline und umging damit den Scrub
	// aus generateAuthBlock - genau die Art Ausnahme, die eine Zusicherung
	// stillschweigend aushebelt.
	baseBlock := generateAuthBlock(cfg.AuthURL, cfg.AuthPaths, cfg.AuthExcept, cfg.AuthGroups)

	// Add 4 more spaces to each line (convert 4-space to 8-space indentation)
	lines := strings.Split(baseBlock, "\n")
	for i, line := range lines {
		if line != "" {
			lines[i] = "    " + line
		}
	}
	return strings.Join(lines, "\n")
}

// WriteConfig writes a Caddyfile configuration for a service
func (m *CaddyManager) WriteConfig(cfg *CaddyConfig) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	// Letzte Verteidigungslinie vor einem Schreibzugriff ausserhalb des
	// Typverzeichnisses: filepath.Join loest "../" auf, statt es abzuweisen.
	fileName := cfg.ConfigKey() + ".conf"
	if err := validateConfigFileName(fileName); err != nil {
		return err
	}

	// Bei einem Typwechsel muss die alte Datei weg. Das passiert weiter unten,
	// NACH dem erfolgreichen Schreiben der neuen: wuerde erst geloescht und das
	// Schreiben danach scheitern, bliebe die Site ganz ohne Konfiguration.
	oldTypePath := ""
	if oldCfg, exists := m.configs[cfg.ConfigKey()]; exists && oldCfg.Type != cfg.Type {
		oldTypePath = filepath.Join(m.hostsDir, oldCfg.Type, fileName)
	}

	// Unregister from allowlist manager if allowlist was removed
	if oldCfg, exists := m.configs[cfg.ConfigKey()]; exists && len(oldCfg.Allowlist) > 0 && len(cfg.Allowlist) == 0 {
		if m.allowlistManager != nil {
			m.allowlistManager.Unregister(cfg.ConfigKey())
			log.Printf("Unregistered allowlist for %s (removed)", cfg.ConfigKey())
		}
	}

	// Get template for this type
	tmpl, ok := templates[cfg.Type]
	if !ok {
		return fmt.Errorf("unknown config type: %s", cfg.Type)
	}

	// Format domains for Caddy: https://a.com, https://b.com
	var formattedDomains []string
	for _, d := range cfg.Domains {
		formattedDomains = append(formattedDomains, "https://"+d)
	}

	// Replace placeholders
	content := tmpl
	content = strings.ReplaceAll(content, "{{NETWORK}}", cfg.Network)
	content = strings.ReplaceAll(content, "{{DOMAINS}}", strings.Join(formattedDomains, ", "))
	content = strings.ReplaceAll(content, "{{UPSTREAM}}", cfg.Upstream)

	// Generate imports block
	var imports []string
	if cfg.Logging {
		imports = append(imports, "    import logging")
	}
	if cfg.DNSProvider != "http" {
		imports = append(imports, fmt.Sprintf("    import tls-%s", cfg.DNSProvider))
	}
	if cfg.Compression {
		imports = append(imports, "    import compression")
	}
	if cfg.Header {
		imports = append(imports, "    import header")
	}
	// Auth handling:
	// - For internal/cloudflare types: auth is inside handle block (for stealth - external gets 404)
	// - For external with allowlist: auth is inside handle @allowed block (added by generateAllowlistBlock)
	// - For external without allowlist: auth is in imports
	if cfg.Auth && cfg.Type == TypeExternal && len(cfg.Allowlist) == 0 {
		if cfg.AuthURL != "" {
			// Custom auth server URL
			imports = append(imports, generateAuthBlock(cfg.AuthURL, cfg.AuthPaths, cfg.AuthExcept, cfg.AuthGroups))
		} else if len(cfg.AuthPaths) == 0 && len(cfg.AuthExcept) == 0 && len(cfg.AuthGroups) == 0 {
			// Protect entire site with local tinyauth (no groups restriction)
			imports = append(imports, "    import auth")
		} else {
			// Protect only specific paths or all except specific paths with local tinyauth
			// Or has group restrictions
			imports = append(imports, generateAuthBlock("", cfg.AuthPaths, cfg.AuthExcept, cfg.AuthGroups))
		}
	}
	if !cfg.SEO {
		imports = append(imports, "    import noindex")
	} else if len(cfg.SEONoindexTypes) > 0 {
		// SEO enabled but certain file types should be noindexed
		imports = append(imports, generateSEONoindexTypesBlock(cfg.SEONoindexTypes))
	}
	if cfg.Performance {
		imports = append(imports, "    import performance")
	}
	if cfg.Security {
		imports = append(imports, "    import security")
	}
	if cfg.WordPress {
		imports = append(imports, "    import wordpress")
	}
	// Import errors for AUTH_GROUPS on external type without allowlist
	// (internal/cloudflare types already have stealth which imports errors)
	// (external with allowlist also has stealth)
	if cfg.Type == TypeExternal && len(cfg.Allowlist) == 0 && cfg.Auth && len(cfg.AuthGroups) > 0 {
		imports = append(imports, "    import errors")
	}
	content = strings.ReplaceAll(content, "{{IMPORTS}}", strings.Join(imports, "\n"))

	// Handle allowlist placeholder (external type only)
	allowlistBlock := m.generateAllowlistBlock(cfg)
	content = strings.ReplaceAll(content, "{{ALLOWLIST_BLOCK}}", allowlistBlock)

	// Generate auth block for internal and cloudflare types (inside handle block for stealth)
	if cfg.Type == TypeInternal || cfg.Type == TypeCloudflare {
		authBlock := ""
		if cfg.Auth {
			// Generate auth block with proper indentation (8 spaces for inside handle block)
			authBlock = m.generateAuthBlockForHandle(cfg) + "\n"
		}
		content = strings.ReplaceAll(content, "{{AUTH_BLOCK}}", authBlock)
	}

	// Generate reverse_proxy block for internal and cloudflare types
	if cfg.Type == TypeInternal {
		rpBlock := m.generateReverseProxyBlock(cfg, "        ", realIPDirective())
		content = strings.ReplaceAll(content, "{{REVERSE_PROXY_BLOCK}}", rpBlock)
	} else if cfg.Type == TypeCloudflare {
		rpBlock := m.generateReverseProxyBlock(cfg, "        ", "header_up X-Real-IP {header.CF-Connecting-IP}")
		content = strings.ReplaceAll(content, "{{REVERSE_PROXY_BLOCK}}", rpBlock)
	}

	// Append www redirect blocks if enabled
	if cfg.WWWRedirect {
		content += generateWWWRedirectBlocks(cfg.Domains, cfg.DNSProvider)
	}

	// Determine file path: container_network.conf
	dir := filepath.Join(m.hostsDir, cfg.Type)
	path := filepath.Join(dir, fileName)

	// Ensure directory exists
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory: %v", err)
	}
	// Set ownership to 1000:1000
	os.Chown(dir, 1000, 1000)

	// Unveraenderte Dateien nicht neu schreiben. Jeder Schreibvorgang loest
	// ueber inotify einen Caddy-Reload aus; ohne diesen Vergleich wuerde der
	// periodische Reconcile alle fuenf Minuten saemtliche Sites neu laden.
	if existing, err := os.ReadFile(path); err == nil && string(existing) == content {
		if oldTypePath != "" {
			if err := os.Remove(oldTypePath); err != nil && !os.IsNotExist(err) {
				log.Printf("Warning: failed to remove old config %s: %v", oldTypePath, err)
			}
		}
		cfgCopy := *cfg
		m.configs[cfg.ConfigKey()] = &cfgCopy
		return nil
	}

	// Write atomically via temp file
	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write temp file: %v", err)
	}

	if err := os.Rename(tmpPath, path); err != nil {
		os.Remove(tmpPath) // Clean up
		return fmt.Errorf("failed to rename temp file: %v", err)
	}
	// Set ownership to 1000:1000
	os.Chown(path, 1000, 1000)

	// Neue Datei liegt - jetzt darf die alte aus dem vorherigen Typverzeichnis weg.
	if oldTypePath != "" {
		if err := os.Remove(oldTypePath); err == nil {
			log.Printf("Removed old config (type changed): %s", oldTypePath)
		} else if !os.IsNotExist(err) {
			log.Printf("Warning: failed to remove old config %s: %v", oldTypePath, err)
		}
	}

	// Store a copy of config for status reporting (not pointer to avoid mutation issues)
	cfgCopy := *cfg
	m.configs[cfg.ConfigKey()] = &cfgCopy

	return nil
}

// generateAllowlistBlock generates the allowlist block for external type
func (m *CaddyManager) generateAllowlistBlock(cfg *CaddyConfig) string {
	// This function only applies to external type
	if cfg.Type != TypeExternal {
		return ""
	}

	// No allowlist - the shared generator supplies trusted_proxies and, more
	// importantly, the SSO cookie strip. Building the directive by hand here is
	// what previously left external backends receiving the TinyAuth cookie.
	if len(cfg.Allowlist) == 0 {
		return "\n" + m.generateReverseProxyBlock(cfg, "    ", realIPDirective())
	}

	// Get resolved IPs from allowlist manager
	var ips []string
	if m.allowlistManager != nil {
		ips = m.allowlistManager.GetResolvedIPs(cfg.ConfigKey())
	}

	// If no resolved IPs yet, resolve now
	if len(ips) == 0 {
		if m.allowlistManager != nil {
			m.allowlistManager.Register(cfg)
			ips = m.allowlistManager.GetResolvedIPs(cfg.ConfigKey())
		}
	}

	// Generate auth block if needed (for external with allowlist, auth goes inside handle)
	authBlock := ""
	if cfg.Auth {
		authBlock = generateAuthBlock(cfg.AuthURL, cfg.AuthPaths, cfg.AuthExcept, cfg.AuthGroups) + "\n"
	}

	// Same generator as everywhere else, so the SSO cookie strip is not forgotten
	// here either. The template below already indents the first line by eight
	// spaces, so only that leading indentation is removed.
	reverseProxyBlock := strings.TrimLeft(m.generateReverseProxyBlock(cfg, "        ", realIPDirective()), " ")

	// Generate allowlist block (private_ranges always allowed for internal access)
	// Even if DNS fails, we still restrict to private_ranges - never fall back to open access
	if len(ips) == 0 {
		log.Printf("Warning: no resolved IPs for allowlist in %s, restricting to private_ranges only", cfg.ConfigKey())
		return fmt.Sprintf(`
    @allowed {
        remote_ip private_ranges
    }

    handle @allowed {
%s        %s
    }
    import stealth`, authBlock, reverseProxyBlock)
	}

	ipList := FormatAllowlistMatcher(ips)
	return fmt.Sprintf(`
    @allowed {
        remote_ip private_ranges %s
    }

    handle @allowed {
%s        %s
    }
    import stealth`, ipList, authBlock, reverseProxyBlock)
}

// generateWWWRedirectBlocks generates separate site blocks for www to non-www redirects
func generateWWWRedirectBlocks(domains []string, dnsProvider string) string {
	var blocks []string
	for _, domain := range domains {
		tlsImport := ""
		if dnsProvider != "http" {
			tlsImport = fmt.Sprintf("\n    import tls-%s", dnsProvider)
		}
		block := fmt.Sprintf(`
# www redirect
https://www.%s {%s
    redir https://%s{uri} permanent
}`, domain, tlsImport, domain)
		blocks = append(blocks, block)
	}
	return strings.Join(blocks, "\n")
}

// generateAuthBlock generates forward_auth directive with optional group restriction
// If authURL is empty, uses local tinyauth container
// If paths is empty and except is empty, protects entire site
// If paths is set, protects only those paths
// If except is set, protects all EXCEPT those paths
// If groups is set, only allow users with matching groups (returns 403 otherwise)
func generateAuthBlock(authURL string, paths []string, except []string, groups []string) string {
	// Determine auth server
	authServer := "{env.COMPOSE_PROJECT_NAME}-tinyauth-1:3000"
	headerUp := ""

	if authURL != "" {
		authServer = authURL
		// Bei http:// MUSS der Host explizit auf den Upstream gesetzt werden.
		//
		// validateAuthURL laesst inzwischen nur https:// durch, dieser Zweig ist
		// also nicht mehr erreichbar. Er bleibt als zweite Verteidigungslinie
		// stehen: wird die Validierung je gelockert, ist der Bypass unten nicht
		// sofort wieder offen. test/auth-guard.sh prueft beide Ebenen.
		//
		// Sonst traegt die forward_auth-Unteranfrage den Host des CLIENTS. Ist
		// der Auth-Server selbst ein Caddy, passt sie dort zu keinem
		// Site-Block, und Caddy antwortet auf einen nicht zuordenbaren Host mit
		// "200, 0 Bytes". forward_auth liest jedes 2xx als "authentifiziert" -
		// die geschuetzte Seite wird freigegeben, ohne dass der Auth-Dienst je
		// gefragt wurde. Mit Caddy 2.11.4 reproduziert.
		//
		// Bei https:// ist die Zeile NICHT nötig: PR #7454 (v2.11.0) setzt den
		// Host bei TLS-Upstreams selbst, damit Host und SNI zusammenpassen.
		// Dort wuerde sie nur zwei "Unnecessary header_up Host"-Warnungen pro
		// Reload erzeugen. Der Fix deckt aber ausdruecklich nur TLS ab, deshalb
		// die Unterscheidung nach Schema.
		//
		// Der lokale TinyAuth-Pfad bleibt bewusst ohne: TinyAuth leitet den
		// Redirect- und Cookie-Namen aus dem Host ab, ein Ueberschreiben wuerde
		// die Anmeldung brechen. Dort ist es unkritisch, weil TinyAuth kein
		// Host-basiertes Routing macht und jede Anfrage beantwortet.
		if strings.HasPrefix(authURL, "http://") {
			headerUp = "\n        header_up Host {http.reverse_proxy.upstream.hostport}"
		}
	}

	// Generate group restriction block if groups are specified
	groupsBlock := ""
	if len(groups) > 0 {
		// Build regex: (^|,)(group1|group2|group3)(,|$)
		// Gruppennamen werden gequotet, damit ein Name wie ".*" die
		// Autorisierung nicht aufhebt. validateGroup laesst Regex-Metazeichen
		// bereits nicht durch; das hier ist die zweite Verteidigungslinie.
		quoted := make([]string, len(groups))
		for i, g := range groups {
			quoted[i] = regexp.QuoteMeta(g)
		}
		// [[:blank:]]* um die Gruppe: Listen kommen in der Praxis als
		// "users, admins" mit Leerzeichen nach dem Komma. Ohne die Toleranz
		// bekaeme ein berechtigter Nutzer faelschlich 403. Die Wortgrenzen
		// bleiben Komma bzw. Anfang/Ende, ein Teilstring-Treffer ist also
		// weiterhin ausgeschlossen.
		groupsRegex := fmt.Sprintf("(^|,)[[:blank:]]*(%s)[[:blank:]]*(,|$)", strings.Join(quoted, "|"))
		// Die Matcher-Definition bleibt auf Site-Ebene, die error-Direktive
		// wandert in den route-Block - dort entscheidet die Reihenfolge.
		groupsBlock = fmt.Sprintf(`
    @auth-groups-denied {%s
        not header_regexp Remote-Groups %s
    }`, "%s", groupsRegex)
	}

	// Full site auth (no paths, no except)
	//
	// Auch hier der Scrub, obwohl forward_auth jeden Pfad abdeckt: liefert der
	// Auth-Dienst 2xx OHNE einen der kopierten Header, blieb in Caddy
	// 2.10.0-2.11.1 der vom Client gesetzte Wert stehen und erreichte das
	// Backend (GHSA-7r4p-vjf4-gxv4, behoben in 2.11.2). build/Dockerfile pinnt
	// den gleitenden Tag caddy:2.11-alpine - die Zusicherung soll nicht davon
	// abhaengen, welche Patch-Version dort gerade steht.
	if len(paths) == 0 && len(except) == 0 {
		forwardAuth := fmt.Sprintf(`forward_auth %s {
        uri /api/auth/caddy
        copy_headers Remote-User Remote-Email Remote-Groups%s
    }`, authServer, headerUp)

		matchers := ""
		groupsError := ""
		if len(groups) > 0 {
			matchers = strings.TrimPrefix(fmt.Sprintf(groupsBlock, ""), "\n")
			groupsError = "    error @auth-groups-denied 403"
		}
		route := wrapAuthInRoute("    "+forwardAuth, groupsError)
		if matchers == "" {
			return route
		}
		return matchers + "\n" + route
	}

	// Auth with except paths (protect all EXCEPT these)
	if len(except) > 0 {
		exceptList := strings.Join(except, " ")
		forwardAuth := fmt.Sprintf(`forward_auth @auth-paths %s {
        uri /api/auth/caddy
        copy_headers Remote-User Remote-Email Remote-Groups%s
    }`, authServer, headerUp)

		matchers := fmt.Sprintf("    @auth-paths not path %s", exceptList)
		groupsError := ""
		if len(groups) > 0 {
			pathCondition := fmt.Sprintf("\n        not path %s", exceptList)
			matchers += fmt.Sprintf(groupsBlock, pathCondition)
			groupsError = "    error @auth-groups-denied 403"
		}
		return matchers + "\n" + wrapAuthInRoute("    "+forwardAuth, groupsError)
	}

	// Path-based auth (protect only these paths)
	pathList := strings.Join(expandDirectoryPaths(paths), " ")
	forwardAuth := fmt.Sprintf(`forward_auth @auth-paths %s {
        uri /api/auth/caddy
        copy_headers Remote-User Remote-Email Remote-Groups%s
    }`, authServer, headerUp)

	matchers := fmt.Sprintf("    @auth-paths path %s", pathList)
	groupsError := ""
	if len(groups) > 0 {
		pathCondition := fmt.Sprintf("\n        path %s", pathList)
		matchers += fmt.Sprintf(groupsBlock, pathCondition)
		groupsError = "    error @auth-groups-denied 403"
	}
	return matchers + "\n" + wrapAuthInRoute("    "+forwardAuth, groupsError)
}

// expandDirectoryPaths ergaenzt zu jedem Pfad, der auf "/*" endet, denselben
// Pfad ohne dieses Suffix.
//
// Caddys path-Matcher trifft mit "/admin/*" die Pfade /admin/ und /admin/x, aber
// NICHT /admin selbst - mit Caddy 2.11.4 gemessen: dort lieferte /admin die
// geschuetzte Seite ohne jede Authentifizierung. Wer CADDY_AUTH_PATHS=/admin/*
// setzt, meint aber den Adminbereich einschliesslich seiner Wurzel.
//
// Ausdruecklich NUR fuer AUTH_PATHS. Bei AUTH_EXCEPT wuerde dieselbe Ergaenzung
// den Schutz aufheben statt ihn auszuweiten - dort bleibt die Liste exakt so,
// wie sie angegeben wurde.
func expandDirectoryPaths(paths []string) []string {
	seen := make(map[string]bool, len(paths)*2)
	var out []string
	add := func(p string) {
		if p != "" && !seen[p] {
			seen[p] = true
			out = append(out, p)
		}
	}
	for _, p := range paths {
		add(p)
		if strings.HasSuffix(p, "/*") {
			add(strings.TrimSuffix(p, "/*"))
		}
	}
	return out
}

// wrapAuthInRoute setzt einen bedingungslosen Scrub der Identitaets-Header vor
// forward_auth und schliesst beides in einen route-Block ein.
//
// Warum ueberhaupt scrubben: das Backend erfaehrt nur ueber Remote-User,
// Remote-Email und Remote-Groups, wer angemeldet ist - genau dafuer kopiert
// forward_auth sie. Es sind aber gewoehnliche HTTP-Header, die jeder Client
// selbst mitschicken kann. Laeuft forward_auth nur auf bestimmten Pfaden
// (CADDY_AUTH_PATHS/-EXCEPT), greift auf allen anderen niemand ein: ein
// "Remote-User: admin" vom Client landet unveraendert beim Backend.
//
// Warum route: Caddy sortiert request_header NACH forward_auth ein. Ein Scrub
// ausserhalb eines route-Blocks wuerde also genau die Header entfernen, die
// forward_auth gerade aus der Auth-Antwort gesetzt hat - jede Anmeldung waere
// kaputt. Innerhalb von route gilt die geschriebene Reihenfolge, deshalb kann
// hier zuerst bedingungslos geloescht und danach gesetzt werden.
//
// Der Vorteil gegenueber einem Scrub mit eigenem Matcher: dort muesste der
// Matcher das exakte Komplement des Auth-Matchers sein ("not path" zu "path").
// Das ist sicher, solange beide gespiegelt bleiben - hier ist eine Luecke
// konstruktiv nicht moeglich, weil ohne Auth einfach nichts gesetzt wird.
//
// Bei Full-Site-Auth wird das nicht gebraucht: forward_auth deckt jeden Pfad ab
// und copy_headers loescht die Header ohnehin erst und setzt sie dann neu.
func wrapAuthInRoute(forwardAuth, groupsError string) string {
	lines := []string{
		"    route {",
		"        request_header -Remote-User",
		"        request_header -Remote-Email",
		"        request_header -Remote-Groups",
	}
	for _, l := range strings.Split(forwardAuth, "\n") {
		if l == "" {
			continue
		}
		lines = append(lines, "    "+l)
	}
	for _, l := range strings.Split(groupsError, "\n") {
		if l == "" {
			continue
		}
		lines = append(lines, "    "+l)
	}
	lines = append(lines, "    }")
	return strings.Join(lines, "\n")
}

// generateSEONoindexTypesBlock generates a matcher and header directive to noindex specific file types
// Example output for types ["pdf", "doc"]:
//
//	@noindex_files path *.pdf *.doc
//	header @noindex_files X-Robots-Tag "noindex"
func generateSEONoindexTypesBlock(types []string) string {
	if len(types) == 0 {
		return ""
	}

	// Build path patterns: *.pdf *.doc etc.
	var patterns []string
	for _, t := range types {
		// Remove leading dot if present (user might write ".pdf" or "pdf")
		t = strings.TrimPrefix(t, ".")
		patterns = append(patterns, "*."+t)
	}

	return fmt.Sprintf(`    @noindex_files path %s
    header @noindex_files X-Robots-Tag "noindex"`, strings.Join(patterns, " "))
}

// RemoveConfig removes all Caddyfile configurations for a network
// Matches files ending with _network.conf (e.g., container_network.conf)
// Returns true if anything was actually removed (a stored config or a file on
// disk), allowing callers to stay idempotent and avoid repeated work/logging.
func (m *CaddyManager) RemoveConfig(network string) (bool, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	removed := false

	// Das Netzwerk exakt vergleichen, nicht per Dateinamens-Suffix: ConfigKey
	// ist "container_network", und der Key "web_bar_foo_caddy" endet ebenfalls
	// auf "_foo_caddy". Ein Suffix-Match loescht damit beim Aufraeumen von
	// "foo_caddy" die Konfiguration des Netzwerks "bar_foo_caddy" gleich mit.
	targets := make(map[string]bool) // Dateinamen dieses Netzwerks
	var keys []string                // zugehoerige Config-Keys
	for key, cfg := range m.configs {
		if cfg.Network == network {
			targets[key+".conf"] = true
			keys = append(keys, key)
		}
	}

	for _, t := range ValidTypes {
		dir := filepath.Join(m.hostsDir, t)
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}

		for _, entry := range entries {
			if entry.IsDir() {
				continue
			}
			name := entry.Name()
			path := filepath.Join(dir, name)

			// Nach einem Watcher-Neustart ist m.configs leer. Der Dateikopf
			// ("# <network> - auto-generated by watcher") nennt das Netzwerk
			// aber weiterhin exakt, deshalb entscheidet er statt des
			// mehrdeutigen Suffixes. Dateien ohne diesen Kopf sind
			// handgepflegt und werden nicht angefasst.
			if !targets[name] {
				fileNetwork, ok := configFileNetwork(path)
				if !ok || fileNetwork != network {
					continue
				}
			}

			if err := os.Remove(path); err != nil {
				return removed, fmt.Errorf("failed to remove %s: %v", path, err)
			}
			removed = true
		}
	}

	// Den In-Memory-State erst nach erfolgreicher Loeschung nachziehen, damit
	// eine fehlgeschlagene Loeschung die Datei nicht als "nicht mehr verwaltet"
	// zuruecklaesst.
	for _, key := range keys {
		if m.allowlistManager != nil {
			m.allowlistManager.Unregister(key)
		}
		delete(m.configs, key)
		removed = true
	}

	return removed, nil
}

// configFileHeaderSuffix markiert vom Watcher erzeugte Konfigurationen. Der
// Kopf lautet "# <network> - auto-generated by watcher".
const configFileHeaderSuffix = " - auto-generated by watcher"

// configFileNetwork liest das Netzwerk aus dem Kopf einer erzeugten
// Konfiguration. Der zweite Rueckgabewert ist false, wenn die Datei nicht vom
// Watcher stammt.
func configFileNetwork(path string) (string, bool) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}
	line, _, _ := strings.Cut(string(content), "\n")
	line = strings.TrimSpace(line)
	if !strings.HasPrefix(line, "# ") || !strings.HasSuffix(line, configFileHeaderSuffix) {
		return "", false
	}
	return strings.TrimSuffix(strings.TrimPrefix(line, "# "), configFileHeaderSuffix), true
}

// ManagedConfigs returns copies of the configs the watcher manages for a network.
func (m *CaddyManager) ManagedConfigs(network string) []CaddyConfig {
	m.mu.RLock()
	defer m.mu.RUnlock()

	var result []CaddyConfig
	for _, cfg := range m.configs {
		if cfg.Network == network {
			result = append(result, *cfg)
		}
	}
	return result
}

// defaultAbsentGrace ist die Karenz, bevor die Konfiguration eines
// verschwundenen Containers entfernt wird.
//
// Waehrend eines Watchtower-Updates ist ein Container kurzzeitig weg: er wird
// gestoppt, entfernt und neu angelegt. Wird die Config in diesem Fenster
// geloescht, loest das einen Caddy-Reload aus und nimmt die Domain fuer die
// Dauer des Updates aus dem Proxy.
//
// Der Default ist bewusst grosszuegig. Das Fenster ist nicht immer kurz: bei
// verlinkten Containern stoppt Watchtower die ganze Abhaengigkeitskette, und
// ein Health-Check-Wait kann sich hinziehen. Zu langes Warten kostet nur eine
// verspaetet aufgeraeumte Datei - zu kurzes nimmt eine laufende Site vom Netz.
// Ueber CONFIG_CLEANUP_GRACE anpassbar.
const defaultAbsentGrace = 30 * time.Minute

// PruneNetwork entfernt verwaltete Konfigurationen eines Netzwerks, die nicht
// mehr deklariert werden - etwa weil CADDY_DOMAIN aus einem Container entfernt
// oder ein Multi-Service-Suffix gestrichen wurde. Ohne diesen Abgleich bliebe
// die alte Datei liegen und die Domain wuerde weiter auf den Container zeigen.
//
// declared sind die Config-Keys, die dieser Durchlauf erzeugt hat; present die
// Namen der Container, die aktuell im Netz haengen. Die Unterscheidung ist
// wesentlich:
//
//   - Container ist da, deklariert die Config aber nicht mehr -> sofort
//     entfernen. Das ist eine bewusste Aenderung des Nutzers.
//   - Container fehlt -> erst nach absentGrace entfernen. Das kann ein
//     laufendes Update sein.
//
// Angefasst werden ausschliesslich Configs aus m.configs, also solche, die der
// Watcher selbst erzeugt hat. Handgepflegte Dateien in /hosts bleiben
// unberuehrt.
// protected sind Containernamen, deren Konfigurationen unter keinen Umstaenden
// angefasst werden duerfen - etwa weil ihr Inspect fehlschlug oder ihre ENV
// ungueltig ist. Die Liste wirkt unabhaengig von m.configs: nach einem
// Watcher-Neustart ist der Speicher leer, und ohne diesen Schutz wuerde eine
// Datei entfernt, nur weil ihre Konfiguration gerade nicht gelesen werden konnte.
//
// declared sind die Config-Keys, die dieser Durchlauf erzeugt hat. Alles andere
// bekommt AUSNAHMSLOS die Karenz - auch dann, wenn der zugehoerige Container
// nachweislich laeuft.
//
// allowRemoval=false pflegt nur die Uhren, ohne zu loeschen und ohne neue Uhren
// zu starten. Der Aufrufer nutzt das, wenn er den Container-Bestand nicht
// vollstaendig ermitteln konnte: dann ist "nicht deklariert" kein Beleg fuer
// Abwesenheit. Die Uhr eines wieder aufgetauchten Containers muss aber auch in
// diesem Fall zurueckgesetzt werden - sonst laeuft eine alte Uhr weiter und ein
// spaeterer Durchlauf loescht sofort, ohne dass je durchgehend Abwesenheit
// vorlag.
//
// Diese Gleichbehandlung ist Absicht. Eine Sonderregel "Container laeuft, also
// ist das Fehlen der Deklaration endgueltig" war schon einmal da und hat in
// Lasttests Konfigurationen sofort geloescht: die Liste der laufenden Container
// und die Praesenzpruefung sind zwei getrennte Abfragen, und ein waehrend eines
// Watchtower-Updates neu entstandener Container erscheint kurzzeitig nur in
// einer von beiden. Der Zeitablauf ist das einzige Signal, das nicht von der
// Konsistenz zweier Momentaufnahmen abhaengt.
func (m *CaddyManager) PruneNetwork(network string, declared, protected map[string]bool, allowRemoval bool, now time.Time) ([]string, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	// pruneCandidate haelt fest, wo die Datei liegt und welcher Container sie
	// besitzt. owner ist leer, wenn er nicht bekannt ist (Datei ohne
	// In-Memory-Eintrag) - dann muss geraten werden.
	type pruneCandidate struct {
		typ   string
		owner string
	}

	candidates := make(map[string]pruneCandidate)
	for key, cfg := range m.configs {
		if cfg.Network != network {
			continue
		}
		if declared[key] {
			delete(m.absentSince, key)
			continue
		}
		candidates[key] = pruneCandidate{typ: cfg.Type, owner: cfg.OwnerContainer}
	}

	// Nach einem Watcher-Neustart ist m.configs leer, die Dateien von zuvor
	// liegen aber noch da. Ohne diesen Durchgang wuerde eine verwaiste Config
	// nie aufgeraeumt, solange das Netzwerk selbst in Benutzung bleibt. Der
	// Dateikopf identifiziert dabei zuverlaessig, was vom Watcher stammt -
	// handgepflegte Dateien haben ihn nicht.
	for _, t := range ValidTypes {
		dir := filepath.Join(m.hostsDir, t)
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		for _, entry := range entries {
			if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".conf") {
				continue
			}
			key := strings.TrimSuffix(entry.Name(), ".conf")
			if _, known := m.configs[key]; known {
				continue
			}
			if _, seen := candidates[key]; declared[key] || seen {
				continue
			}
			fileNetwork, ok := configFileNetwork(filepath.Join(dir, entry.Name()))
			if !ok || fileNetwork != network {
				continue
			}
			candidates[key] = pruneCandidate{typ: t}
		}
	}

	var pruned []string
	for key, cand := range candidates {
		// Geschuetzt heisst: wir konnten nicht feststellen, was der Container
		// will. Das ist kein Beleg fuer Abwesenheit - eine laufende Uhr wird
		// deshalb zurueckgesetzt, statt weiterzuticken.
		if m.ownerMatches(cand.owner, key, network, protected) {
			delete(m.absentSince, key)
			continue
		}

		if !allowRemoval {
			continue
		}

		since, seen := m.absentSince[key]
		if !seen {
			m.absentSince[key] = now
			log.Printf("Config %s is no longer declared, removing in %s unless it returns", key, m.absentGrace)
			continue
		}
		if now.Sub(since) < m.absentGrace {
			continue
		}

		reason := fmt.Sprintf("undeclared for %s", now.Sub(since).Round(time.Second))
		removed, err := m.removeManagedConfig(key, filepath.Join(m.hostsDir, cand.typ, key+".conf"), reason)
		if err != nil {
			return pruned, err
		}
		if removed {
			pruned = append(pruned, key)
		}
	}

	return pruned, nil
}

// removeManagedConfig loescht eine verwaltete Konfiguration und zieht den
// In-Memory-State nach.
//
// Das Loeschen ist der einzige Pfad, der eine laufende Site aus dem Proxy
// nehmen kann. Er liegt deshalb bewusst an genau einer Stelle.
func (m *CaddyManager) removeManagedConfig(key, path, reason string) (bool, error) {
	log.Printf("Removing config %s (%s)", key, reason)

	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return false, fmt.Errorf("failed to remove %s: %v", path, err)
	}
	if m.allowlistManager != nil {
		m.allowlistManager.Unregister(key)
	}
	delete(m.configs, key)
	delete(m.absentSince, key)
	delete(m.networkGone, key)
	return true, nil
}

// PruneUnknownNetworks entfernt verwaltete Konfigurationen, deren Netzwerk gar
// nicht mehr existiert.
//
// Normalerweise raeumt das network:destroy-Event auf. Laeuft der Watcher in
// genau dem Moment nicht - etwa weil Watchtower ihn gerade aktualisiert -, geht
// das Event verloren. Danach taucht das Netzwerk weder im Reconcile noch im
// Cleanup-Loop je wieder auf, die Datei bliebe also dauerhaft liegen.
//
// existing sind die aktuell vorhandenen Proxy-Netzwerke, stillExists prueft
// einen einzelnen Namen direkt beim Daemon nach.
//
// Die Listenabfrage allein reicht als Grundlage nicht: waere sie aus
// irgendeinem Grund unvollstaendig, wuerden Konfigurationen noch existierender
// Netzwerke geloescht. Vor jedem Loeschen wird deshalb einzeln nachgefragt.
// Zusammen mit der Karenz muss ein Netzwerk also ueber die gesamte Frist
// fehlen UND im Moment des Loeschens nachweislich weg sein.
func (m *CaddyManager) PruneUnknownNetworks(existing map[string]bool, stillExists func(string) bool, now time.Time) ([]string, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	// Ohne Rueckfragemoeglichkeit ist eine leere Liste nicht vertrauenswuerdig
	// genug, um darauf Loeschungen zu stuetzen - sie saehe aus wie "alle
	// Netzwerke weg". Mit stillExists wird ohnehin einzeln nachgefragt, dann
	// darf auch der letzte Rest aufgeraeumt werden.
	if len(existing) == 0 && stillExists == nil {
		return nil, nil
	}

	var pruned []string

	for _, t := range ValidTypes {
		dir := filepath.Join(m.hostsDir, t)
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}

		for _, entry := range entries {
			if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".conf") {
				continue
			}
			path := filepath.Join(dir, entry.Name())

			// Nur eigene Dateien anfassen - handgepflegte haben den Kopf nicht.
			network, ok := configFileNetwork(path)
			if !ok {
				continue
			}

			key := strings.TrimSuffix(entry.Name(), ".conf")

			// Netzwerk ist da: Uhr aus. Ohne diesen Reset liefe eine Uhr aus
			// einem frueheren Durchlauf weiter, und ein spaeteres, echtes
			// Verschwinden wuerde sofort loeschen statt die volle Frist
			// abzuwarten.
			if existing[network] {
				delete(m.networkGone, key)
				continue
			}

			// Beim Daemon nachfragen, BEVOR die Uhr startet - nicht erst vor
			// dem Loeschen. Sonst koennte eine unvollstaendige Liste eine Uhr
			// fuer ein Netzwerk starten, das es noch gibt; verschwindet das
			// Netz dann kurz vor Fristende, wuerde sofort geloescht, obwohl es
			// nie durchgehend gefehlt hat.
			if stillExists != nil && stillExists(network) {
				delete(m.networkGone, key)
				continue
			}

			since, seen := m.networkGone[key]
			if !seen {
				m.networkGone[key] = now
				log.Printf("Config %s belongs to a network that no longer exists, removing in %s", key, m.absentGrace)
				continue
			}
			if now.Sub(since) < m.absentGrace {
				continue
			}

			removed, err := m.removeManagedConfig(key, path, fmt.Sprintf("network %s gone for %s", network, now.Sub(since).Round(time.Second)))
			if err != nil {
				return pruned, err
			}
			if removed {
				pruned = append(pruned, key)
			}
		}
	}

	return pruned, nil
}

// ownerMatches prueft, ob die Config eines Containers in der uebergebenen
// Namensmenge vorkommt.
//
// Ist der Besitzer bekannt (Config stammt aus diesem Prozess), entscheidet ein
// exakter Namensvergleich. Nur fuer Dateien ohne In-Memory-Eintrag - also nach
// einem Watcher-Neustart - muss aus dem Dateinamen geraten werden. Compose
// benennt Container "<projekt>-<service>-<nummer>", der Key ist
// "<container>_<network>" bzw. im Multi-Service-Modus
// "<container>-<service>_<network>".
func (m *CaddyManager) ownerMatches(owner, key, network string, names map[string]bool) bool {
	if len(names) == 0 {
		return false
	}
	if owner != "" {
		return names[owner]
	}

	container := strings.TrimSuffix(key, "_"+network)
	if names[container] {
		return true
	}
	// Multi-Service: der Servicename haengt hinten dran.
	for name := range names {
		if strings.HasPrefix(container, name+"-") {
			return true
		}
	}
	return false
}

// ListConfigs returns all configuration files
func (m *CaddyManager) ListConfigs() []ConfigInfo {
	m.mu.RLock()
	defer m.mu.RUnlock()

	var result []ConfigInfo
	types := ValidTypes

	for _, t := range types {
		dir := filepath.Join(m.hostsDir, t)
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}

		for _, entry := range entries {
			if entry.IsDir() {
				continue
			}
			name := entry.Name()
			if !strings.HasSuffix(name, ".conf") {
				continue
			}
			// Skip example files
			if strings.HasSuffix(name, ".example") {
				continue
			}

			path := filepath.Join(dir, name)
			configKey := strings.TrimSuffix(name, ".conf")
			domains := extractDomainsFromConfig(path)

			// Parse container and network from filename (container_network)
			container := ""
			network := configKey
			if idx := strings.LastIndex(configKey, "_"); idx > 0 {
				container = configKey[:idx]
				network = configKey[idx+1:]
			}

			// Check if this is a managed (watcher-generated) config
			cfg, isManaged := m.configs[configKey]

			// Get allowlist from stored config (most accurate source)
			var allowlist []string
			if isManaged && len(cfg.Allowlist) > 0 {
				allowlist = cfg.Allowlist
			}

			// Build config info
			info := ConfigInfo{
				Network:   network,
				Container: container,
				Type:      t,
				Domains:   domains,
				Allowlist: allowlist,
				Path:      path,
				Managed:   isManaged,
			}

			// Use stored config for feature flags (managed configs only)
			if isManaged {
				info.Logging = cfg.Logging
				info.DNSProvider = cfg.DNSProvider
				info.Compression = cfg.Compression
				info.Header = cfg.Header
				info.Auth = cfg.Auth
				info.AuthPaths = cfg.AuthPaths
				info.AuthExcept = cfg.AuthExcept
				info.AuthGroups = cfg.AuthGroups
				info.AuthURL = cfg.AuthURL
				info.SEO = cfg.SEO
				info.SEONoindexTypes = cfg.SEONoindexTypes
				info.WWWRedirect = cfg.WWWRedirect
				info.Performance = cfg.Performance
				info.Security = cfg.Security
				info.WordPress = cfg.WordPress
				info.TrustedProxies = cfg.TrustedProxies
			} else {
				// Parse imports from manual config file
				content, err := os.ReadFile(path)
				if err == nil {
					parseImportsFromContent(string(content), &info)
				}
			}

			result = append(result, info)
		}
	}

	return result
}

// parseImportsFromContent parses import statements from config content
// and sets the corresponding flags in ConfigInfo
func parseImportsFromContent(content string, info *ConfigInfo) {
	// Default: SEO is true (indexable) unless noindex is imported
	info.SEO = true

	lines := strings.Split(content, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)

		// Parse import statements
		if strings.HasPrefix(line, "import ") {
			importName := strings.TrimPrefix(line, "import ")
			importName = strings.TrimSpace(importName)

			switch importName {
			case "logging":
				info.Logging = true
			case "tls", "tls-cloudflare":
				info.DNSProvider = "cloudflare"
			case "tls-hetzner":
				info.DNSProvider = "hetzner"
			case "compression":
				info.Compression = true
			case "header":
				info.Header = true
			case "noindex":
				info.SEO = false
			case "performance":
				info.Performance = true
			case "security":
				info.Security = true
			case "wordpress":
				info.WordPress = true
			case "auth":
				info.Auth = true
			}
		}

		// Parse trusted_proxies directive
		// Format: trusted_proxies private_ranges 1.2.3.4 5.6.7.8
		if strings.HasPrefix(line, "trusted_proxies") {
			parts := strings.Fields(line)
			// Skip "trusted_proxies" and optionally "private_ranges"
			var proxies []string
			for i := 1; i < len(parts); i++ {
				if parts[i] != "private_ranges" {
					proxies = append(proxies, parts[i])
				}
			}
			if len(proxies) > 0 {
				info.TrustedProxies = proxies
			}
		}
	}

	// Check for www redirect (separate server block with redir)
	// Pattern: www.domain { ... redir https://domain ... }
	if strings.Contains(content, "www.") && strings.Contains(content, "redir ") && strings.Contains(content, "permanent") {
		info.WWWRedirect = true
	}
}

// extractDomainsFromConfig reads a config file and extracts domains
func extractDomainsFromConfig(path string) []string {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil
	}

	var domains []string
	lines := strings.Split(string(content), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		// Look for lines starting with https://
		if strings.HasPrefix(line, "https://") {
			// Parse domains: "https://a.com, https://b.com {"
			line = strings.TrimSuffix(line, "{")
			line = strings.TrimSpace(line)
			parts := strings.Split(line, ",")
			for _, part := range parts {
				part = strings.TrimSpace(part)
				part = strings.TrimPrefix(part, "https://")
				if part != "" {
					domains = append(domains, part)
				}
			}
			// Continue to find all domain blocks in file
		}
	}

	return domains
}

// Wildcard certificate template
var wildcardTemplate = `# Wildcard certificate for *.{{DOMAIN}}
# Auto-generated by watcher - do not edit manually
# Services using subdomains of {{DOMAIN}} will automatically use this certificate

*.{{DOMAIN}} {
    import tls-{{DNS_PROVIDER}}
    import stealth
}
`

// WriteWildcardConfigs generates wildcard certificate configs for the specified domains
func (m *CaddyManager) WriteWildcardConfigs(domains []string, dnsProvider string) error {
	if len(domains) == 0 {
		return nil
	}

	// Wildcards go into hosts root directory (global configs like base.conf)
	dir := m.hostsDir

	// Ensure directory exists
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory: %v", err)
	}
	os.Chown(dir, 1000, 1000)

	if err := validateWildcardDNSProvider(dnsProvider); err != nil {
		return fmt.Errorf("WILDCARD_DNS_PROVIDER: %w", err)
	}

	for _, domain := range domains {
		// Die Domain wird Teil des Dateinamens und des Caddyfiles - beides
		// braucht dieselbe Pruefung wie eine CADDY_DOMAIN.
		if !isValidDomain(domain) {
			return fmt.Errorf("invalid wildcard domain: %s", domain)
		}
		filename := fmt.Sprintf("wildcard.%s.conf", domain)
		if err := validateConfigFileName(filename); err != nil {
			return err
		}
		path := filepath.Join(dir, filename)

		// Generate content from template
		content := wildcardTemplate
		content = strings.ReplaceAll(content, "{{DOMAIN}}", domain)
		content = strings.ReplaceAll(content, "{{DNS_PROVIDER}}", dnsProvider)

		// Write atomically via temp file
		tmpPath := path + ".tmp"
		if err := os.WriteFile(tmpPath, []byte(content), 0644); err != nil {
			return fmt.Errorf("failed to write temp file: %v", err)
		}

		if err := os.Rename(tmpPath, path); err != nil {
			os.Remove(tmpPath)
			return fmt.Errorf("failed to rename temp file: %v", err)
		}
		os.Chown(path, 1000, 1000)

		log.Printf("Generated wildcard config: wildcard.%s.conf", domain)
	}

	return nil
}

// GetWildcardDomains returns the list of configured wildcard domains from config files
func (m *CaddyManager) GetWildcardDomains() []string {
	m.mu.RLock()
	defer m.mu.RUnlock()

	var domains []string

	entries, err := os.ReadDir(m.hostsDir)
	if err != nil {
		return domains
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		// Match wildcard.*.conf pattern
		if strings.HasPrefix(name, "wildcard.") && strings.HasSuffix(name, ".conf") {
			// Extract domain: wildcard.example.com.conf -> example.com
			domain := strings.TrimPrefix(name, "wildcard.")
			domain = strings.TrimSuffix(domain, ".conf")
			domains = append(domains, domain)
		}
	}

	return domains
}
